// <auto-generated />
using System;
using Gr_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gr_Api.Migrations
{
    [DbContext(typeof(GrContext))]
    partial class GrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CY_DM.CyCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CySkinId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("rootId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CySkinId");

                    b.HasIndex("rootId");

                    b.ToTable("CyCategory");
                });

            modelBuilder.Entity("CY_DM.CySkin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CySkin");
                });

            modelBuilder.Entity("CY_DM.GrCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("rootId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("rootId");

                    b.ToTable("GrCategory");
                });

            modelBuilder.Entity("CY_DM.GrKeyValue", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("GrProductID")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GrProductID");

                    b.ToTable("GrKeyValue");
                });

            modelBuilder.Entity("CY_DM.GrManufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("GrManufacturer");
                });

            modelBuilder.Entity("CY_DM.GrProduct", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatasheetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrCategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("GrManufacturerID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFullyGet")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmartImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GrCategoryID");

                    b.HasIndex("GrManufacturerID");

                    b.ToTable("GrProduct");
                });

            modelBuilder.Entity("CY_DM.CyCategory", b =>
                {
                    b.HasOne("CY_DM.CySkin", "CySkin")
                        .WithMany()
                        .HasForeignKey("CySkinId");

                    b.HasOne("CY_DM.CyCategory", "rootCategory")
                        .WithMany("childItems")
                        .HasForeignKey("rootId");

                    b.Navigation("CySkin");

                    b.Navigation("rootCategory");
                });

            modelBuilder.Entity("CY_DM.GrCategory", b =>
                {
                    b.HasOne("CY_DM.CyCategory", "rootCategory")
                        .WithMany()
                        .HasForeignKey("rootId");

                    b.Navigation("rootCategory");
                });

            modelBuilder.Entity("CY_DM.GrKeyValue", b =>
                {
                    b.HasOne("CY_DM.GrProduct", "GrProduct")
                        .WithMany("GrKeyValue")
                        .HasForeignKey("GrProductID");

                    b.Navigation("GrProduct");
                });

            modelBuilder.Entity("CY_DM.GrProduct", b =>
                {
                    b.HasOne("CY_DM.GrCategory", "GrCategory")
                        .WithMany()
                        .HasForeignKey("GrCategoryID");

                    b.HasOne("CY_DM.GrManufacturer", "GrManufacturer")
                        .WithMany()
                        .HasForeignKey("GrManufacturerID");

                    b.Navigation("GrCategory");

                    b.Navigation("GrManufacturer");
                });

            modelBuilder.Entity("CY_DM.CyCategory", b =>
                {
                    b.Navigation("childItems");
                });

            modelBuilder.Entity("CY_DM.GrProduct", b =>
                {
                    b.Navigation("GrKeyValue");
                });
#pragma warning restore 612, 618
        }
    }
}
