// <auto-generated />
using System;
using CY_WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CY_WebApi.Migrations
{
    [DbContext(typeof(CyContext))]
    [Migration("20251226170210_userUpdateB")]
    partial class userUpdateB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CY_DM.CyAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CyUserID");

                    b.ToTable("CyAddress");
                });

            modelBuilder.Entity("CY_DM.CyCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CySkinId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("rootId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CySkinId");

                    b.HasIndex("rootId");

                    b.ToTable("CyCategory");
                });

            modelBuilder.Entity("CY_DM.CyCoupon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("CyCoupon");
                });

            modelBuilder.Entity("CY_DM.CyCouponUsage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRequested")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CouponId");

                    b.HasIndex("UserId");

                    b.ToTable("CyCouponUsages");
                });

            modelBuilder.Entity("CY_DM.CyFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FileIQ")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SenderID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SenderID");

                    b.ToTable("CyFile");
                });

            modelBuilder.Entity("CY_DM.CyGuarantee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompanyExplaination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyUserID")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuaranteeCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuaranteeID")
                        .HasColumnType("int");

                    b.Property<string>("GuarantreePrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductProblem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecievedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CyUserID");

                    b.HasIndex("GuaranteeID")
                        .IsUnique();

                    b.ToTable("CyGuarantee");
                });

            modelBuilder.Entity("CY_DM.CyInspectionForm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Baking")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyAddressID")
                        .HasColumnType("int");

                    b.Property<int?>("ExternalVisualInspection")
                        .HasColumnType("int");

                    b.Property<Guid?>("File")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HeatedChemicalTest")
                        .HasColumnType("int");

                    b.Property<int?>("InternalVisualInspection")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("KeyFunctional")
                        .HasColumnType("int");

                    b.Property<int?>("Lab")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PinCorrelationTest")
                        .HasColumnType("int");

                    b.Property<int?>("ProgrammingTest")
                        .HasColumnType("int");

                    b.Property<int?>("Radiography")
                        .HasColumnType("int");

                    b.Property<int?>("SolderabilityAnalysis")
                        .HasColumnType("int");

                    b.Property<int?>("TapeAndReel")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("XRFTest")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CyAddressID");

                    b.HasIndex("UserID");

                    b.ToTable("CyInspectionForm");
                });

            modelBuilder.Entity("CY_DM.CyInspectionItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CyInspectionFormID")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TargetDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CyInspectionFormID");

                    b.ToTable("CyInspectionItem");
                });

            modelBuilder.Entity("CY_DM.CyKeyData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CyKeyData");
                });

            modelBuilder.Entity("CY_DM.CyListMail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CyListMail");
                });

            modelBuilder.Entity("CY_DM.CyManufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CyManufacturer");
                });

            modelBuilder.Entity("CY_DM.CyMenu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CyMenus");
                });

            modelBuilder.Entity("CY_DM.CyMenuItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CyMenuId")
                        .HasColumnType("int");

                    b.Property<int?>("CySkinId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Meta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.Property<string>("PageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isProduct")
                        .HasColumnType("bit");

                    b.Property<int?>("rootId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CyCategoryId");

                    b.HasIndex("CyMenuId");

                    b.HasIndex("CySkinId");

                    b.HasIndex("rootId");

                    b.ToTable("CyMenuItem");
                });

            modelBuilder.Entity("CY_DM.CyOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyUserID")
                        .HasColumnType("int");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<double?>("FanalTotalAmount")
                        .HasColumnType("float");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderToTasvieh")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Taxes")
                        .HasColumnType("float");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CyUserID");

                    b.ToTable("CyOrder");
                });

            modelBuilder.Entity("CY_DM.CyOrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyOrderID")
                        .HasColumnType("int");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("CyOrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("CyOrderItem");
                });

            modelBuilder.Entity("CY_DM.CyOrderMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeenDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SenderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TicketID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("SenderID");

                    b.HasIndex("TicketID");

                    b.ToTable("CyOrderMessage");
                });

            modelBuilder.Entity("CY_DM.CyPcbForm", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BoardThickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BomExcell")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CuThicknessBottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuThicknessLayers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuThicknessPlanes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuThicknessTop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuttingLayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPC_A_610_G")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPCstandardIPC_A_600")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Layers")
                        .HasColumnType("int");

                    b.Property<bool>("MechanizedَََAssembly")
                        .HasColumnType("bit");

                    b.Property<string>("PCBmaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PCBquantity")
                        .HasColumnType("int");

                    b.Property<int>("PCBquantityTwo")
                        .HasColumnType("int");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlaceAndPick")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SilkScreenColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilkScreenLayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolderMask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolderMaskColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolderMaskLayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolderMaskThickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoliderPaste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StackedLayers")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurfaceFinish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("ViaFilling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ZipFile")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("CyPcbForm");
                });

            modelBuilder.Entity("CY_DM.CyProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CyManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("CyProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DatasheetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfrNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NoOffPrice")
                        .HasColumnType("float");

                    b.Property<string>("PartNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PartnerPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("Price2")
                        .HasColumnType("float");

                    b.Property<double?>("Price3")
                        .HasColumnType("float");

                    b.Property<double?>("Price4")
                        .HasColumnType("float");

                    b.Property<double?>("Price5")
                        .HasColumnType("float");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ShopPrice")
                        .HasColumnType("float");

                    b.Property<string>("SmallImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Supply")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CyCategoryId");

                    b.HasIndex("CyManufacturerId");

                    b.HasIndex("CyProductCategoryId");

                    b.ToTable("CyProduct");
                });

            modelBuilder.Entity("CY_DM.CyProductCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<int?>("RootId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RootId");

                    b.ToTable("CyProductCategory");
                });

            modelBuilder.Entity("CY_DM.CyProductPriceAndWarranty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CyProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoOffUnitPrice")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CyProductId");

                    b.ToTable("CyProductPriceAndWarranty");
                });

            modelBuilder.Entity("CY_DM.CyProductSpec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CyProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CyProductCategoryId");

                    b.HasIndex("CyProductId");

                    b.ToTable("CyProductSpec");
                });

            modelBuilder.Entity("CY_DM.CyProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CyProfile");
                });

            modelBuilder.Entity("CY_DM.CySkin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CySkin");
                });

            modelBuilder.Entity("CY_DM.CySub_Cat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyCategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("CySubjectID")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CyCategoryID");

                    b.HasIndex("CySubjectID");

                    b.ToTable("CySub_Cats");
                });

            modelBuilder.Entity("CY_DM.CySubject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BigImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CySkinId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateExp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateShow")
                        .HasColumnType("datetime2");

                    b.Property<string>("Describtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EditorState")
                        .HasColumnType("int");

                    b.Property<string>("Extra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAuthenticate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.Property<string>("PreTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmallImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bodyString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CreateById");

                    b.HasIndex("CyCategoryId");

                    b.HasIndex("CySkinId");

                    b.ToTable("CySubject");
                });

            modelBuilder.Entity("CY_DM.CyTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CyUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("bit");

                    b.Property<int?>("Important")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TaskKind")
                        .HasColumnType("int");

                    b.Property<int>("TaskState")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AdminId");

                    b.HasIndex("CyUserID");

                    b.ToTable("CyTask");
                });

            modelBuilder.Entity("CY_DM.CyTicket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("CyTicket");
                });

            modelBuilder.Entity("CY_DM.CyUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double?>("AccountBalance")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CyHsPs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CyUsNm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MelliCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartnerStatus")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserBalanceStatus")
                        .HasColumnType("int");

                    b.Property<string>("UserCodeA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCodeB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isPartner")
                        .HasColumnType("bit");

                    b.Property<int>("userType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CyUser");
                });

            modelBuilder.Entity("CY_DM.HardWare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quntity")
                        .HasColumnType("int");

                    b.Property<int?>("SysPCId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SysPCId");

                    b.ToTable("HardWare");
                });

            modelBuilder.Entity("CY_DM.SysPC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustmerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustmerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFactor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ShopSale")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("SysPC");
                });

            modelBuilder.Entity("CY_DM.CyAddress", b =>
                {
                    b.HasOne("CY_DM.CyUser", "CyUser")
                        .WithMany()
                        .HasForeignKey("CyUserID");

                    b.Navigation("CyUser");
                });

            modelBuilder.Entity("CY_DM.CyCategory", b =>
                {
                    b.HasOne("CY_DM.CySkin", "CySkin")
                        .WithMany()
                        .HasForeignKey("CySkinId");

                    b.HasOne("CY_DM.CyCategory", "rootCategory")
                        .WithMany("childItems")
                        .HasForeignKey("rootId");

                    b.Navigation("CySkin");

                    b.Navigation("rootCategory");
                });

            modelBuilder.Entity("CY_DM.CyCouponUsage", b =>
                {
                    b.HasOne("CY_DM.CyCoupon", "Coupon")
                        .WithMany("Coupons")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CY_DM.CyUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CY_DM.CyFile", b =>
                {
                    b.HasOne("CY_DM.CyUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CY_DM.CyGuarantee", b =>
                {
                    b.HasOne("CY_DM.CyUser", "CyUser")
                        .WithMany()
                        .HasForeignKey("CyUserID");

                    b.Navigation("CyUser");
                });

            modelBuilder.Entity("CY_DM.CyInspectionForm", b =>
                {
                    b.HasOne("CY_DM.CyAddress", "CyAddress")
                        .WithMany()
                        .HasForeignKey("CyAddressID");

                    b.HasOne("CY_DM.CyUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CyAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CY_DM.CyInspectionItem", b =>
                {
                    b.HasOne("CY_DM.CyInspectionForm", null)
                        .WithMany("Items")
                        .HasForeignKey("CyInspectionFormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CY_DM.CyMenuItem", b =>
                {
                    b.HasOne("CY_DM.CyCategory", "CyCategory")
                        .WithMany()
                        .HasForeignKey("CyCategoryId");

                    b.HasOne("CY_DM.CyMenu", "CyMenu")
                        .WithMany("CyMenuItems")
                        .HasForeignKey("CyMenuId");

                    b.HasOne("CY_DM.CySkin", "CySkin")
                        .WithMany()
                        .HasForeignKey("CySkinId");

                    b.HasOne("CY_DM.CyMenuItem", "rootMenuItem")
                        .WithMany("childItems")
                        .HasForeignKey("rootId");

                    b.Navigation("CyCategory");

                    b.Navigation("CyMenu");

                    b.Navigation("CySkin");

                    b.Navigation("rootMenuItem");
                });

            modelBuilder.Entity("CY_DM.CyOrder", b =>
                {
                    b.HasOne("CY_DM.CyUser", "CyUser")
                        .WithMany()
                        .HasForeignKey("CyUserID");

                    b.Navigation("CyUser");
                });

            modelBuilder.Entity("CY_DM.CyOrderItem", b =>
                {
                    b.HasOne("CY_DM.CyOrder", "CyOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("CyOrderID");

                    b.HasOne("CY_DM.CyProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");

                    b.Navigation("CyOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CY_DM.CyOrderMessage", b =>
                {
                    b.HasOne("CY_DM.CyOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID");

                    b.HasOne("CY_DM.CyUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID");

                    b.HasOne("CY_DM.CyTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketID");

                    b.Navigation("Order");

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CY_DM.CyPcbForm", b =>
                {
                    b.HasOne("CY_DM.CyUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CY_DM.CyProduct", b =>
                {
                    b.HasOne("CY_DM.CyCategory", "CyCategory")
                        .WithMany()
                        .HasForeignKey("CyCategoryId");

                    b.HasOne("CY_DM.CyManufacturer", "CyManufacturer")
                        .WithMany("CyProducts")
                        .HasForeignKey("CyManufacturerId");

                    b.HasOne("CY_DM.CyProductCategory", "CyProductCategory")
                        .WithMany()
                        .HasForeignKey("CyProductCategoryId");

                    b.Navigation("CyCategory");

                    b.Navigation("CyManufacturer");

                    b.Navigation("CyProductCategory");
                });

            modelBuilder.Entity("CY_DM.CyProductCategory", b =>
                {
                    b.HasOne("CY_DM.CyProductCategory", "RootCategory")
                        .WithMany("Childs")
                        .HasForeignKey("RootId");

                    b.Navigation("RootCategory");
                });

            modelBuilder.Entity("CY_DM.CyProductPriceAndWarranty", b =>
                {
                    b.HasOne("CY_DM.CyProduct", "CyProduct")
                        .WithMany("PricesAndWarranties")
                        .HasForeignKey("CyProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CyProduct");
                });

            modelBuilder.Entity("CY_DM.CyProductSpec", b =>
                {
                    b.HasOne("CY_DM.CyProductCategory", "CyProductCategory")
                        .WithMany()
                        .HasForeignKey("CyProductCategoryId");

                    b.HasOne("CY_DM.CyProduct", "CyProduct")
                        .WithMany("Specifications")
                        .HasForeignKey("CyProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CyProduct");

                    b.Navigation("CyProductCategory");
                });

            modelBuilder.Entity("CY_DM.CySub_Cat", b =>
                {
                    b.HasOne("CY_DM.CyCategory", "CyCategory")
                        .WithMany()
                        .HasForeignKey("CyCategoryID");

                    b.HasOne("CY_DM.CySubject", "CySubject")
                        .WithMany()
                        .HasForeignKey("CySubjectID");

                    b.Navigation("CyCategory");

                    b.Navigation("CySubject");
                });

            modelBuilder.Entity("CY_DM.CySubject", b =>
                {
                    b.HasOne("CY_DM.CyUser", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateById");

                    b.HasOne("CY_DM.CyCategory", "CyCategory")
                        .WithMany()
                        .HasForeignKey("CyCategoryId");

                    b.HasOne("CY_DM.CySkin", "CySkin")
                        .WithMany()
                        .HasForeignKey("CySkinId");

                    b.Navigation("CreateBy");

                    b.Navigation("CyCategory");

                    b.Navigation("CySkin");
                });

            modelBuilder.Entity("CY_DM.CyTask", b =>
                {
                    b.HasOne("CY_DM.CyUser", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("CY_DM.CyUser", "CyUser")
                        .WithMany()
                        .HasForeignKey("CyUserID");

                    b.Navigation("Admin");

                    b.Navigation("CyUser");
                });

            modelBuilder.Entity("CY_DM.CyTicket", b =>
                {
                    b.HasOne("CY_DM.CyUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CY_DM.HardWare", b =>
                {
                    b.HasOne("CY_DM.SysPC", "SysPC")
                        .WithMany("HardWare")
                        .HasForeignKey("SysPCId");

                    b.Navigation("SysPC");
                });

            modelBuilder.Entity("CY_DM.CyCategory", b =>
                {
                    b.Navigation("childItems");
                });

            modelBuilder.Entity("CY_DM.CyCoupon", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("CY_DM.CyInspectionForm", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CY_DM.CyManufacturer", b =>
                {
                    b.Navigation("CyProducts");
                });

            modelBuilder.Entity("CY_DM.CyMenu", b =>
                {
                    b.Navigation("CyMenuItems");
                });

            modelBuilder.Entity("CY_DM.CyMenuItem", b =>
                {
                    b.Navigation("childItems");
                });

            modelBuilder.Entity("CY_DM.CyOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CY_DM.CyProduct", b =>
                {
                    b.Navigation("PricesAndWarranties");

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("CY_DM.CyProductCategory", b =>
                {
                    b.Navigation("Childs");
                });

            modelBuilder.Entity("CY_DM.CyTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CY_DM.SysPC", b =>
                {
                    b.Navigation("HardWare");
                });
#pragma warning restore 612, 618
        }
    }
}
